######################################################################
# Automatically generated by qmake (2.01a) Sa. Aug 30 14:20:20 2014
######################################################################

TEMPLATE = app
TARGET = test_libweerc

PRE_TARGETDEPS += ../libweerc/libweerc.a
INCLUDEPATH += . ../libweerc/src
LIBS = ../libweerc/libweerc.a

QMAKE_CXXFLAGS += -std=c++0x -O0
QMAKE_LFLAGS += -std=c++0x -O0

QT += gui
QT += network
CONFIG += debug

# Input
SOURCES += src/main.cpp src/mainwindow.cpp src/bufferlistmodel.cpp src/bufferlinesmodel.cpp
HEADERS += src/mainwindow.h src/bufferlistmodel.h src/bufferlinesmodel.h
FORMS += ui/mainwindow.ui

# libweerc
lwrc.target = ../libweerc/libweerc.a
lwrc.commands = cd ../libweerc && make
lwrc.depends =
QMAKE_EXTRA_TARGETS += lwrc
