######################################################################
# Automatically generated by qmake (2.01a) Sa. Aug 30 14:20:20 2014
######################################################################

TEMPLATE = app
TARGET = test_libweerc

PRE_TARGETDEPS += ../libweerc/libweerc.a
INCLUDEPATH += . ../libweerc/src
LIBS = ../libweerc/libweerc.a

QMAKE_CXXFLAGS += -std=c++0x -O0
QMAKE_LFLAGS += -std=c++0x -O0

QT -= gui
QT += network
CONFIG += console debug

# Input
SOURCES += src/main.cpp

# libweerc
lwrc.target = ../libweerc/libweerc.a
lwrc.commands = cd ../libweerc && make
lwrc.depends =
QMAKE_EXTRA_TARGETS += lwrc
