######################################################################
# Automatically generated by qmake (2.01a) Sa. Aug 30 14:20:20 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src ../libweerc/
INCLUDEPATH += .
LIBS = ../libweerc/libweerc.a

depends = ../libweerc

QMAKE_CXXFLAGS += -std=c++0x -O0
QMAKE_LFLAGS += -std=c++0x -O0

QT -= gui
QT += network
CONFIG += console debug

# Input
SOURCES += src/main.cpp
